### ISSUE TITLE
SMSAPI is not a constructor

### ISSUE THREAD

**Issue by lukaszniemkiewicz** [smsapi/smsapi-javascript-client#71]
importing the library in  nestjs (express, typescript) ends with error: `SMSAPI is not a constructor`
tried all possible versions from 1.0 to 2.0.11.
node: v.16.15.1

code:
```
import { Controller, Get } from '@nestjs/common';
import { SMSAPI } from 'smsapi';

@Controller('sms')
export class SmsController {



    @Get()
    async testSms() {

        const smsapi = new SMSAPI('Bxxxxxxxxxxxxxxxxxxxxxxxxxi');

        try {
            const result = smsapi.sms.sendSms('+486xxxxxxxxx', 'My first message!');

            console.log(result);
        } catch (err) {
            console.log(err);

        }
    }
}
```

error: 

```
express-server | [Nest] 842   - 11/29/2023, 8:23:20 AM   [ExceptionsHandler] smsapi_1.SMSAPI is not a constructor +52636550ms
express-server | TypeError: smsapi_1.SMSAPI is not a constructor
express-server |     at SmsController.test2 (/usr/src/app/dist/src/sms/sms.controller.js:17:24)
express-server |     at /usr/src/app/node_modules/@nestjs/core/router/router-execution-context.js:38:29
express-server |     at InterceptorsConsumer.intercept (/usr/src/app/node_modules/@nestjs/core/interceptors/interceptors-consumer.js:11:20)
express-server |     at /usr/src/app/node_modules/@nestjs/core/router/router-execution-context.js:46:60
express-server |     at /usr/src/app/node_modules/@nestjs/core/router/router-proxy.js:9:23
express-server |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
express-server |     at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
express-server |     at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:112:3)
express-server |     at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
express-server |     at /usr/src/app/node_modules/express/lib/router/index.js:281:22
```

**Comment by pdziewa** [comment]
Hey!

I tested sending a message using a freshly installed NestJS with this code:

```ts
import { Controller, Get } from '@nestjs/common';
import { AppService } from './app.service';
import { SMSAPI } from 'smsapi';

@Controller()
export class AppController {
  constructor(private readonly appService: AppService) {}

  @Get()
  async getHello(): Promise<string> {
    const smsapi = new SMSAPI('***');

    try {
      const response = await smsapi.sms.sendSms('***', 'Test message');

      console.log(response);
    } catch (error) {
      console.error(error);
    }

    return this.appService.getHello();
  }
}
```

And everything works fine.

Versions:
- Node: `16.15.1`, `16.20.2`, `20.10.0`
- NestJS: `10.2.10`
- TS: `5.3.2`
- SMSAPI: `2.0.11`

**Comment by lukaszniemkiewicz** [comment]
updating nestjs to new version solved the problem

Thank you, regards.
